services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: pei_user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pei_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
